from tinkoff.constants import PRODUCTION

TOKEN_SANDBOX = 't.MtPwL4XJWUF_-jUqsDcKBn6hyCPAtnvKIE2_AverGyT5y1o9cFG6IOvhVe6OUvNtAl8GwfMShMP3bDYobFJDmA'
TOKEN_PRODUCTION = 't.ug4DyflGRDihloIt8kg4uvLpVi3ztdC9p7nq8LqtEmWoYxQWaZnZPE8kb89CC8plfSBKD1dh1xlPx7aBISK0ew'
BROCKER_ACC = 'SB146552'
HEADER_AUTH = f'Bearer {TOKEN_PRODUCTION if PRODUCTION else TOKEN_SANDBOX}'
